server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/its-lahiru/microservice-project-service-config
          search-paths:
            - 'service-config/*service'
